### ISSUE TITLE
Define research question or target variable

### ISSUE THREAD

**Issue by suleenwong** [eaunaicr97/TheGreenCitySolutionsGroup#12]

**Comment by eaunaicr97** [comment]
Project target:
Our goal is to sell an energy controller. The product balance the energy consumption to reduce the building(s) energy consumption. 

The city commissioned a study to find how to balance the grid and reduce the CO2. 

Who is our stockholder:
**- Building owner. Real estate company.**
- A company that sells solar panels/renewable energy components. (Removed)
- Grid provider. Optimised to balance the energy through the grid. Stabilise the grid. ()
- City. 
CO2

**Comment by eaunaicr97** [comment]
Stockholder 
Energy Provider.

**Comment by Leee-P** [comment]
Stockholder could be a Municipal quarter management and or municipal energy provider. Weather forecast, day-ahead electricity price forecast, solar and wind power forecast, net energy usage forecast for a hole grid are commercially available. But forecast of energy usage in a smaller scale (building/quarter/suburb/city) can help improving energy management locally.
